### ISSUE TITLE
Should success criteria support fetching data by date?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#18]
For the  [Vitals IG](http://argonautwiki.hl7.org/index.php?title=Vital_Signs) and [Labs IG](http://argonautwiki.hl7.org/index.php?title=Laboratory_Results) the support for search based on category code and date is _Should_,   Should the support for this be _Mandatory_ instead?

Exanple:

`GET http://fhir2.healthintersections.com.au/open/Observation?patient=555580&category=vital-signs&date=ge2015-01-14`

**Comment by jmandel** [comment]
This falls out from #32
