### ISSUE TITLE
How to resolve the inconsistencies between CCDA, MU3, and the Argonaut Vital Signs IG?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#22]
For the  [Vitals IG](http://argonautwiki.hl7.org/index.php?title=Vital_Signs) the LOINC codes and concepts were taken from the [C-CDA Vital Sign Result value set](http://hl7-fhir.github.io/daf/valueset-daf-observation-CCDAVitalSignResult.html) which is the same as in DAF.  However in order to create a list of more generic concepts and to align with  [MU3 Common Core Data Set](https://www.healthit.gov/sites/default/files/2015Ed_CCG_CCDS.pdf),  the following changes have been prooposed and inconsistencies have been identified.  Note that these codes changes would not align with the existing C-CDA:
1. **3141-9** Body weight Measured Body weight Mass Pt ^Patient Qn Measured --> **29463-7** Body weight Mass Pt ^Patient Qn 
   - [Tracker made to update CCDA to this code](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=964 C-CDA DSTU comment 964)
2. Should **8306-3** Body length  be removed from the list?
   -  Head circumference not listed in the Common Core Data Set clarifications document
   - it can be a translation (i,e, child of ) **8302-2**  Body height 
3.  Should **8287-5** Head Occipital-frontal circumference by Tape measure --> 9843-4  Head Occipital-frontal circumference
4. Should **59574-4**  Body mass index (BMI) [Percentile]  be used instead of **39156-5** Body mass index (BMI) [kg/m2] ?
   -  In the Common Core Data Set clarifications document, BMI is listed as percentile instead of kg/m2
   -  in light of the fact that you need a reference chart to measure the percentile against and that is not defined as far as I know? 
5. Should **3140-1** Body surface area (BSA) be removed from the list? 
   -  BSA is not listed in the Common Core Data Set clarifications document.
6. Should **Inhaled oxygen concentration** be added to list?
   -  The Common Core Data Set clarifications document mentions Inhaled oxygen concentration. (assuming this is used to intepret of O2 conc measurement - e.g. room air, 40% O2 etc)
7. Should **8306-3**Body length be removed since is being subsumed by **8302-2** height?

comparison table 

| C-CDA | current Argonaut IG | based on MU3 guidacne |
| --- | --- | --- |
| 9279-1 Respiratory rate | Respiratory Rate  9279-1  /min | Respiratory Rate  9279-1  /min |
| 8867-4 Heart rate | Heart rate  8867-4  /min | Heart rate  8867-4  /min |
| 2710-2 Oxygen saturation in Capillary blood by Oximetry | Oxygen saturation  2708-6   % | Oxygen saturation  2708-6   % |
| 55284-4 Blood pressure systolic and diastolic | Blood pressure systolic and diastolic  55284-4  — | Blood pressure systolic and diastolic  55284-4 |
| 8480-6 Systolic blood pressure | Systolic blood pressure  8480-6  mm[Hg] | Systolic blood pressure  8480-6  mm[Hg] |
| 8462-4 Diastolic blood pressure | Diastolic blood pressure  8462-4  mm[Hg] | Diastolic blood pressure  8462-4  mm[Hg} |
| 8310-5 Body temperature | Body temperature  8310-5  Cel | Body temperature  8310-5  Cel |
| 8302-2 Body height | Body height  8302-2  cm | Body height  8302-2  cm |
| 8306-3 Body height --lying | Body length  8306-3  cm |  |
| 8287-5 Head Occipital-frontal circumference by Tape measur | Head circumference  8287-5  cm | **8287-5 Head Occipital-frontal circumference by Tape measure vs 9843-4  Head Occipital-frontal circumference** |
| 3141-9 Body weight Measured | Body weight  3141-9  g, kg | **29463-7 Body weight Mass Pt ^Patient Qn** |
| 39156-5 Body mass index (BMI) [Ratio] | Body mass index  39156-5  kg/m2 | **Body mass index  39156-5  kg/m2 vs  59574-4 Body mass index (BMI) [Percentile]** ? |
| 3140-1 Body surface area Derived from formula | Body surface area  3140-1  m2 |  |
| 59408-5 Oxygen saturation in Arterial blood by Pulse oximetry | Oxygen saturation  2708-6   % |  |
| 8478-0 Mean blood pressure | Mean blood pressure  8478-0  mm[Hg] | Mean blood pressure  8478-0  mm[Hg] |
| - | - | **Inhaled oxygen concentration??** |

**Comment by Healthedata1** [comment]
C-CDA will be updating: [Body Weight code to  29463-7 Body weight](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=964)  And the Argo IG will be updated accordingly as well.

**Comment by michelle-m-miller** [comment]
In the event that BSA remains, then will it be changed to a methodless LOINC?

3140-1 has a method of derived whereas 8277-6 is methodless.

**Comment by Healthedata1** [comment]
1) Since there is no mention of BSA in the [2015 Edition Certification Companion Guide
](https://www.healthit.gov/sites/default/files/2015Ed_CCG_CCDS.pdf), I am removing from the Vitals IG and creating an extensibly bound [Argonaut Valueset ](http://argonautwiki.hl7.org/index.php?title=Argonaut_Vital_Signs) based on the DAF Valueset

2) Based on HL7 SD call the C-CDA code for O2 saturation will be 59408-5 (Oxygen saturation in Arterial blood by Pulse oximetry) instead of using the methodless code 2708-6 (Oxygen saturation in Arterial blood) use in the argonaut IG.  Argonaut and DAF will follow this decision as well.
