### ISSUE TITLE
Should Category based search for Vitals and Lab IG be mandatory?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#24]
For the  [Vitals IG](http://argonautwiki.hl7.org/index.php?title=Vital_Signs) and [Labs IG](http://argonautwiki.hl7.org/index.php?title=Laboratory_Results) the search for all results are based upon using the Observation.category element to fetch all the relevent results.  There is no other easy way to do this using the [FHIR Restful API](http://hl7-fhir.github.io/http.html).

example search using category:
**GET [base]/Observation?patient=[id]&category=vital-signs**

```
GET https://fhir-open-api-dstu2.smarthealthit.org/Observation?patient=1186747&category=vital-signs
```

**Comment by michelle-m-miller** [comment]
On a related note (this was the closest open issue I could find to add this comment):

When searching by category of vital-signs and assuming the table of LOINCs is a minimum data set that can be extended, then the following blurb may need to be clarified or loosened up a bit:

Each Observation must have: 
 a LOINC code which tells you what is being measured and is taken from the "LOINC Code" column in the table below

**Comment by Healthedata1** [comment]
The decision to use category codes for fetching is a key part the Argonaut API.
