### ISSUE TITLE
What is the status of an implantable device that is no longer in the patient?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#27]
The current search criteria for all implants associated with a patient does not indicate if they are still affixed to the patient.  I would propose that 'not-available' be used to indicate the device is no longer implanted.  But the current status codes for Device are not sufficient to convey if the device is in the patient (see below) 

| Code | Display | Definition |
| --- | --- | --- |
| available | Available | The Device is available for use. |
| not-available | Not Available | The Device is no longer available for use (e.g. lost, expired, damaged). |
| entered-in-error | Entered in Error | The Device was entered in error and voided. |

**Comment by torresdrew** [comment]
The status of the device reflects the status in an inventory system. The procedure resource would be more appropriate to convey that the device has been implanted or explanted.

The definition of device.status:
Status of the Device availability.

**Comment by Healthedata1** [comment]
Status is not required so will remove from the draft IG  But I think will
need to discuss on OO call what it means if have both a status and Patient.

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com
