### ISSUE TITLE
Should Problem Search criteria include both all Problems and all Active Problems?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#28]
This is similar to the Allergies issue  is in regards search based upon the mandatory clinicalStatus element in the Condition resource.
[From the 2014 Certification for Summary of Care **](https://www.cms.gov/Regulations-and-Guidance/Legislation/EHRIncentivePrograms/downloads/Stage2_EPCore_15_SummaryCare.pdf)

Problem List – At a minimum a list of current, active and historical diagnoses. We do not limit the EP to
just including diagnoses on the problem list.

Should we  support both search for all conditions (a.k.a. problems) for a patient:

`GET /Condition?patient=[id]`

AND  search for all **active** conditions (a.k.a. problems) for a patient?

`GET /Condition?patient=[id]&clinicalstatus=active,relapse,remission`

**Comment by jmandel** [comment]
Yes! `GET /Condition?patient=[id]` should work, to satisfy:

> Problem List – At a minimum a list of current, active and historical diagnoses. We do not limit the EP to just including diagnoses on the problem list.

**Comment by Healthedata1** [comment]
Will provide an [example ](http://argonautwiki.hl7.org/index.php?title=Problems#GET_.2FCondition.3Fpatient.3D.5Bid.5D.26category.3Dproblem.26clinicalstatus.3Dactive.2Crelapse.2Cremission)but not require limit by active problems
