### ISSUE TITLE
Should SNOMED CT be preferred over UNII for food and environmental allergens?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#29]
Based upon recent [feedback ](https://groups.google.com/forum/?hl=en#!topic/argonaut-fhir-data-query-team/RX7OE22usiQ) The current code system guidelines may be outdated and unsuitable.

current guidelines are:

> AllergyIntolerance.substance is bound to a Value set (Code set) consisting of:
> - NDF-RT codes for drug class allergies
> - RxNorm codes limited to term types (TTY) , 'IN' ingredient, 'MIN' multiple ingredient, and 'PIN' precise ingredient for drug ingredient allergies
> - UNII codes for other substance allergies
> - SNOMED CT if no other code from above code systems are available.

Should we update to these guidelines?:

> AllergyIntolerance.substance is bound to a Value set (Code set) consisting of:
> - NDF-RT codes for drug class allergies
> - RxNorm codes limited to term types (TTY) , 'IN' ingredient, 'MIN' multiple ingredient, and 'PIN' precise ingredient for drug ingredient allergies
> - SNOMED CT if no other code from above code systems are available.

**Comment by jmandel** [comment]
Let's eliminate the UNII requirement, focus on SNOMED, and close this issue :) 

(UNII only appeared in our sprint because I put it there, and I'm convinced we should drop it.)

**Comment by Healthedata1** [comment]
updated IG.
