### ISSUE TITLE
DAF Substance Value Set is not aligned with Allergies code guidelines

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#31]
[DAF Substance FHIR Value set](http://hl7.org/fhir/daf/valueset-daf-substance.html)  is not filtered properly for RxNorm.[1].

**Comment by brettmarquard** [comment]
Tracker DAF 9736 http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=9736&start=0

**Comment by michelle-m-miller** [comment]
I noticed that the gForge 9736 has term types of IN, MIN, PIN, or BN
By contrast, Argonaut IG only has IN, MIN, PIN.
Is the exclusion of BN from Argonaut IG an intentional variance from the DAF change request?

**Comment by brettmarquard** [comment]
Thank you for pointing out. I updated Argonaut IG to include BN.

**Comment by jmandel** [comment]
Do we really want to record allergies as specifically to brand name drugs? It creates a mapping challenge (i.e. An opportunity to _miss_ drug/allergy interactions) and I can't see what it gains us.

**Comment by brettmarquard** [comment]
Thank you Josh, there is an alternative discussion in SDWG that MIN shouldn’t be included.

I will bring both questions to the SDWG call on 4/28http://wiki.hl7.org/index.php?title=20160428_sdwg_agenda. I believe everyone benefits when we can get C-CDA and FHIR/Argonaut value sets aligned.

**Comment by jmandel** [comment]
Ok, thanks @brettmarquard! The thing about `MIN` is that, as far as as I can see, sometimes that's all you know. As in, "we gave you a combined ingredient pill and you didn't tolerate it well."

**Comment by Healthedata1** [comment]
Currently this is a preferred binding in DAF.  For this IG  I recommend we make it extensible  ( allows for text which is a potential concern)

**Comment by Healthedata1** [comment]
Brett to follow up.
