### ISSUE TITLE
What are the ONC Guidelines regarding approach to Date and Date range based searches?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#32]
There is a desire to limit the quantity of data returned and be able to limit the date range for searching, but the ONC guidance is unclear.  Need to Follow up with ONC regarding approach to Date and Date-Range-based searches in the MU3 world. [More on this topic](https://groups.google.com/forum/?hl=en#!topic/argonaut-fhir-data-query-team/DrOS3rBLJcE)

**Comment by brettmarquard** [comment]
Additional data may be included.

Per ONC certification companion guide (https://www.healthit.gov/sites/default/files/2015Ed_CCG_g8-Application-access-data-category-request.pdf): 

> The API must be able to send, at a minimum all required data for a specified date
> range(s). We acknowledge that there will be organizational policies and/or safety best
> practices that will dictate **additional data to be sent and when data is considered complete
> and/or ready for being sent**. This should be appropriately described in the API
> documentation

**Comment by jmandel** [comment]
We expect to treat this case-by-case.

For example:
- **No need** for date-based search in: Meds, Problems, Allergies
- **Yes need** for date-based search in: Vitals, Labs, ...

**Comment by torresdrew** [comment]
We(Cerner) received additional clarification on the recent release of the companion guide. ICSA labs, the certifying body for 2015 CEHRT program, has stated that as long as the documentation outlines when a date parameter is permitted, there will be no conflict with the certification requirements. Their latest test scripts also reflect this clarification.
