### ISSUE TITLE
How to resolve the difference between the MU sex codes and FHIR gender codes

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#34]
| concept | The ONC 2015 certification rule | FHIR |
| --- | --- | --- |
| Male | M | male |
| Female | F | female |
| Unknown | UNK | unknown |
| Other |  | other |

  The latest [ONC Certification Companion Guide](https://www.healthit.gov/sites/default/files/2015Ed_CCG_CCDS.pdf)  reiterates the requirement to send M, F, and UNK. An extension to the argo or DAF or is required to restrict the base valueset usage to these three elements.  [More discussion](https://groups.google.com/forum/?hl=en#!topic/argonaut-project/AdSCF9wr_jg)  [and here too](https://groups.google.com/forum/?hl=en#!topic/argonaut-project/_9OhpF64dU0)

**Comment by brettmarquard** [comment]
Response from ONC: Latest [https://www.healthit.gov/sites/default/files/2015Ed_CCG_CCDS.pdf ONC Certification Companion Guide] reiterates the requirement to send M, F, and UNK for **birth sex**.

To support this request an extension or update to FHIR base specification is required.

**Comment by brettmarquard** [comment]
Discussed on 4/15/2016 internal Argonaut call and we will define an extension.

(clarification from ONC may change this direction in the future)

**Comment by brettmarquard** [comment]
Tracker DAF 9736 [http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=9736&start=0](url)

**Comment by Healthedata1** [comment]
This raises the complication of whether to require the gender in the IG or birth sex in the IG and on which to query.  Currently Gender is mandatory but Birth sex is listed as a 2015 MU "must support"

**Comment by Healthedata1** [comment]
To clarify:
- The Query is on the fhir gender element 
- Birth Sex extension is a MU2015 must support.
