### ISSUE TITLE
Should Problems be limited by category?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#35]
Based on 4/19 Call decision made to limit by category = Problems.
This aligns with Code Set = SNOMED and allows for the Condition resource to be use for Concerns and Diagnosis with separate code bindings.

Thus define the argo category codes as:

|  |  |  |  |
| --- | --- | --- | --- |
| **Code** | **Code System** | **Code System OID** | **Print Name** |
| ? | ? | ? | Health Concern |
| 282291009 | SNOMED CT | 2.16.840.1.113883.6.96 | Diagnosis |
| 55607006 | SNOMED CT | 2.16.840.1.113883.6.96 | Problem |

( since these are not orthogonal conceptually need to determine how they fit together - heirarchy, translations, ?)

`GET /Condition?patient=[id]`

Will be 

`GET /Condition?patient=[id]&category=55607006  will get all active and historical problems`

**Comment by torresdrew** [comment]
This is what a category table would look like for the 3 concepts shared by this resource:
Concerns = "Additional Health Concerns"
Problems = "Problems"[SNOMED code listed above](provider concerns)
Diagnosis = "Diagnoses" (ICD codes for billing)

The IG text should should highlight that "GET /Condition?patient=[id]" would result in problems, concerns, and diagnoses being returned.

If we go down the path of 3 separate profiles on the condition resource then we would also required specific values for the category. A problem profile would include, at a minimum, the agreed on category, and any additional categories that the vendor may include.

**Comment by jmandel** [comment]
I'm not sure I understand separation of diagnosis from problem: wouldn't both be part of the same MU CCDS category? 

And no matter what: Could we could pick codes that are easier for humans to understand, so the query URLs are more straightforward?  This wouldn't be to the exclusion of standard codes like SNOMED, but perhaps in addition. 

Particularly if we don't even _have_ a standard code for "health concern" it might be best to simply publish a small value set with "nice" category codes. Like for Labs,where the categories are "nice" (even though we could have used less nice standardized categories). 

So we could have:

```
GET /Condition?patient=[id]&category=concern
GET /Condition?patient=[id]&category=problem 
```

**Comment by torresdrew** [comment]
> I'm not sure I understand separation of diagnosis from problem: wouldn't both be part of the same MU CCDS category?

You can't do that and be compliant with the certification requirements. The requirements state that the problem code be SNOMED. Diagnoses are generally ICD codes. The requirement is that active problems be returned. Diagnoses are technically out of scope with regards to certification requirements.

**Comment by Healthedata1** [comment]
I agree Josh will change to easy codes. also looking "forward" to concerns this solves that issue and not really sure where Dx falls in.  Categorization is a messy thing.

so update cat codes to 

|  |  |  |
| --- | --- | --- |
| **Code** | **Code System** | **Print Name** |
| concern | http://hl7.org/fhir/condition-category | Health Concern |
| diagnosis | http://hl7.org/fhir/condition-category | Diagnosis |
| problem | http://hl7.org/fhir/condition-category | Problem |

[And IG updated as well!](http://argonautwiki.hl7.org/index.php?title=Problems)

**Comment by Healthedata1** [comment]
> If we go down the path of 3 separate profiles on the condition resource
> then we would also required specific values for the category. A problem
> profile would include, at a minimum, the agreed on category, and any
> additional categories that the vendor may include.

That is what we had decided and I updated the IG accordingly.  With this
change I don't think we need to add the part about the search resulting in
extra stuff being returned

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by michelle-m-miller** [comment]
I think more clarity is needed on the definition of a "concern" category because technically problems are concerns, too.

Is the intent of a search by category = concern to return ALL concerns (by HL7 definition -- which includes concerns from all stakeholders and perspectives)?

Or, is the intent of a search by category = concern to return ONLY the "Additional Concerns" (by ONC/SD definition -- e.g. patient, related person, and other care team member concerns NOT represented on the provider's the problem list)?

**Comment by jmandel** [comment]
As far as I can tell, our objective in supporting this search parameter would be to ensure that we can supply a data category level search API as required in the regulations.

**Comment by Healthedata1** [comment]
Yes so Michelle has identified the  boundaries the we are going with for this:

|  |  |  |  |
| --- | --- | --- | --- |
| **Code** | **Code System** | **Print Name** | Definition |
| concern | http://hl7.org/fhir/condition-category | Health Concern | Concerns from other stakeholders which are outside the provider's problem list. |
| problem | http://hl7.org/fhir/condition-category | Problem | The patients problems as identified by the provider(s). Items on the provider's problem list |
|  |  |  |  |

**Comment by Healthedata1** [comment]
will update both problems and  health concern's IG to reflect this

**Comment by michelle-m-miller** [comment]
FYI -- the updates to the problem and concern IG have references to Observation (which I assume is an artifact of copy/paste and should be updated to Condition instead)

**Comment by Healthedata1** [comment]
fixed - thank you
