### ISSUE TITLE
Category Code discrepency

### ISSUE THREAD

**Issue by avinashshanbhag** [argonautproject/implementation-program#36]
The value set pointed by the Category Code (http://hl7.org/fhir/condition-category) does not have "Problem" or "concern" as represented in the IG. I may be looking at the wrong version. But, wanted to bring it up just in case an update is needed.

**Comment by Healthedata1** [comment]
I updated to (http://hl7.org/fhir/argo-condition-category) this is a locally defined extension. The intent is to register this code system but it has not been done yet.   I need to determine where it should be done.

**Comment by michelle-m-miller** [comment]
DAF has a preferred binding to http://hl7.org/fhir/valueset-condition-category.html
IG references two new codes, but I don't see the value set that defines the two new codes (problem + concern)

What is the value set binding for condition.category?  Specifically, will there be a new value set that is a union of the existing DAF value set (so we have a code for Diagnosis) + the new Argonaut value set (so we have codes for problem and concern)?

**Comment by Healthedata1** [comment]
Hi Michelle,

There is an issue tracker here
https://github.com/argonautproject/implementation-program/issues/36.
(which you found) In summary we need to define code system for these values
and then the new valueset.  Frankly right now I stubbed in a codesystem.  I
will be creating these artifacts locally on the wiki as a temporary home.
The harmonization with DAF is planned I will make a tracker for DAF

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by michelle-m-miller** [comment]
FYI -- SNOMED 55607006 for Problems

**Comment by Healthedata1** [comment]
Added a codesystem:
- [http://argonautwiki.hl7.org/extension-codes](http://argonautwiki.hl7.org/index.php?title=Argonaut_Condition_Category_Codes)

and created a valueset:
-  [http://argonautwiki.hl7.org/ValueSet/argo-condition-category-codes](http://argonautwiki.hl7.org/index.php?title=Argonaut_Extension_Codes)

Created DAF tracker [[#10106]](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=10106)
Plan is to work out the boundaries with DAF and to eventually migrate to a full IG using the build tools.    

RE MMM comment on SNOMED, For DSTU 2 category codes used FHIR codesystems and we have decided to continue with this same pattern.
