### ISSUE TITLE
What syntax for search must servers support?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#39]
The decision was made to not support compartment based searches.  However in FHIR there several syntax are allowed for search.  The documentation uses the following syntax:

`GET [base]/[Resource-type]?patient=24342{&other parameters}`

but we do not state that this is the only syntax allowed.

This issue has been discussed on the[ list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/argonaut-project/srjnfhNBQbk/VgfY1HzVAAAJ) where the equivalent syntax have been identified:

`GET [base]/[Resource-type]?Subject=[id]{&other parameters}`
`GET [base]/[Resource-type]?Subject=Patient/[id]{&other parameters}`
`GET [base]/[Resource-type]?Subject._id=[id]{&other parameters}`
`GET [base]/[Resource-type]?subject:Patient=[id]{&other parameters}`
`GET [base]/[Resource-type]?subject:Patient=Patient/[id]{&other parameters}`
`GET [base]/[Resource-type]?subject:Patient=https://[url]/Patient/id{&other parameters}`
`GET [base]/[Resource-type]?subject:Patient._id=[id]{&other parameters}`
`GET [base]/[Resource-type]?patient:Patient=https://[url]/Patient/id{&other parameters}`

**Comment by brettmarquard** [comment]
Servers MAY support all of the above. For Argonaut, the minimum bar is on each resource wiki page.

**Comment by jmandel** [comment]
I'm a bit confused about this "minimum bar" concept. Are you saying that an
Argonaut sever must accept "?patient=123" but is free to refuse
"?patient=Patient/123"?

**Comment by brettmarquard** [comment]
Does 'refuse' = 'not support'?

My working assumption is if we aren't explicit then it's not fair to say what a system supports. I am happy to discuss if that is a bad assumption.

**Comment by jmandel** [comment]
By "refuse" I mean... not recognize as identical in meaning to "?patient=123".

**Comment by brettmarquard** [comment]
Sorry, now I am confused.

Do you think we need to be explicit about what searches a system supports?

**Comment by jmandel** [comment]
Well, yes we should be explicit! That doesn't mean we have to repeat everything _everywhere_, but we should say it in one place and reference it from everywhere else.

**Comment by Healthedata1** [comment]
We would say it [here](http://argonautwiki.hl7.org/index.php?title=Implementation_Guide&action=edit&section=17).  Any server side opposition to this?

**Comment by Healthedata1** [comment]
will document search syntax as discussed above
