### ISSUE TITLE
Whether to search Assessment and Plan of Treatment and Goals by status = 'active'

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#40]
The [Assessment and Plan of Treatment](http://argonautwiki.hl7.org/index.php?title=Assessment_and_Plan_of_Treatment) uses the CarePlan resource and is currently drafted to support search by status='active'.   The CarePlan statuses are listed [here](http://hl7.org/fhir/valueset-care-plan-status.html).  

The [Goals](http://argonautwiki.hl7.org/index.php?title=Goals) uses the Goal resource and is currently drafted to support search by status='in-progress'.   The Goal statuses are listed [here](http://hl7.org/fhir/valueset-goal-status.html).

Should these IGs require the capability to search by these statuses?

**Comment by torresdrew** [comment]
I don't think we should require the status search query. May/should support language should be used for status based filtering.

**Comment by Healthedata1** [comment]
Base on 20160606 Call will not require status based searches.

**Comment by Healthedata1** [comment]
On 07/12/2016 call was a request for status based search will add Should support language should be used for status based filtering.
