### ISSUE TITLE
Whether CareTeam needs to support search by status and/or date?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#41]
Since the 2015 CCDS provide no guidance on fetching care teams member information it is unclear what the search criteria are.  Logically, the current care team is relevant when seeking this information.  This would correspond to the status = 'in-progress'

`GET/CarePlan?Patient=[id]&category=careteam&status=in=progress`

**Comment by torresdrew** [comment]
Where is the status in-progress found? "proposed | draft | active | completed | cancelled" are the statuses available for the CarePlan resource. Were you looking at the detail section of the resource which has "not-started | scheduled | in-progress | on-hold | completed | cancelled"?

Date would not apply to CareTeam. We were going down the same path that the category of CareTeam on the CarePlan resource would get you the team, and no category would give you multiple CarePlans: Actual patient/provider CarePlans and CareTeam.

**Comment by Healthedata1** [comment]
Re status. 
Thanks for catching that error. I will fix that. 

Re category
Since are proposing the care plan resource for both care team and plan and assessment.
Options 
 Do a category search on care plan.  Category code = assess-plan (Loinc: 51847-2 Eval+plan note. But LOINC  scale  = Doc. ) 

Other?

**Comment by torresdrew** [comment]
I think that category code would work for CarePlan, and like the concept of a category search to separate the 2 concepts if the consumer wants to. It would also facilitate certification category requirements.

CareTeam may be a difficult concept to find a standard code for. Do we know if structured doc came up with a CareTeam section in C-CDA?

**Comment by Healthedata1** [comment]
For category we will use are own argonaut extension codes like we did for problems and health concerns.   I'll update the wiki to reflect this.

**Comment by brettmarquard** [comment]
There is not a CareTeam section in C-CDA.

The members are associated where relevant – encounter provider in encounters section, primary care in header, etc.

**Comment by torresdrew** [comment]
Fair enough. I thought those were context specific and not really the patient CareTeam, but I don't want to open that can of worms. :-D

**Comment by brettmarquard** [comment]
Oh the can is open….

Structured Docs will include guidance on how to record the Care Team in a C-CDA companion guide which will be balloted this fall.

**Comment by Healthedata1** [comment]
based on 20160606 Call will base search on "active"  care team members and not a date based search.
