### ISSUE TITLE
Multiple races and ethnicities for patient

### ISSUE THREAD

**Issue by torresdrew** [argonautproject/implementation-program#42]
Does using extension allow for us to represent multiple ethnicities and races?

**Comment by brettmarquard** [comment]
Yes.

In DAF we included the following note:

Specifying multiple race codes: Many systems may capture race codes at a very granular level which can be rolled up to higher level race codes such as "Asian", "White" etc. In cases where these systems intend to include these granular race codes in addition to the higher level race codes permitted by the value set they can do so by using the coding element which can be repeated as many times as needed within the race element.

http://hl7.org/fhir/daf/patient-daf.html

**Comment by torresdrew** [comment]
Thanks for the clarification. I just noticed the extension type was CodeableConcept. I was getting hung up on the cardinality of 0..1 on the extension which makes sense now.

**Comment by jmandel** [comment]
I'm not sure repeated codings actually express the right meaning here. The
note cited is about different granularities on a single race concept (where
multiple codings makes sense) but the original question was about
representing multiple _races_.

**Comment by torresdrew** [comment]
Josh is correct. The intent of the question was to understand how to represent a patient that makes the statement, "I am White and Asian." 

The CodeableConcept makes sense to roll up Alaska Indian to American Indian or Alaska Native, but represent them both by separate codes:
1737-6  Alaska Indian   Alaska Indian   Race & Ethnicity - CDC
1002-5  American Indian or Alaska Native    American Indian or Alaska Native

The same would apply for ethnicity. A patient may make the statement, "I am Mexican and Scottish."
2116-2  Scottish    Scottish
2148-5  Mexican Mexican

**Comment by brettmarquard** [comment]
Thanks for the example.

This may require a few updates to DAF -- I am not certain updating to 0..\* with the current value set (http://hl7.org/fhir/daf/valueset-daf-race.html) will meet the policy intent.

**Comment by torresdrew** [comment]
The value set constraint would have to be loosened as well for the extension. The CDC race and ethnicity codes would suffice[1].

[1]https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.6.238

**Comment by Healthedata1** [comment]
See FHIR tracker [#8794](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=8794&start=0)

I noticed this a while back when creating the US Lab Patient Profile.  This is a problem with US-core extension.  We could easily create a temporary argonaut extension until us-core can correct?

**Comment by torresdrew** [comment]
Has there been thoughts about this issue? We are working through the ontology, and believe the above values should be used for race and ethnicity instead of the FHIR valuesets for race and ethnicity. Since what is above is called out by the regulatory text.

[1]http://hl7.org/fhir/v3/Ethnicity/index.html
[2]http://hl7.org/fhir/v3/Race/index.html

**Comment by brettmarquard** [comment]
Two issues:
1. [#8794](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=8794&start=0) addresses the update to support multiple races and ethnicities.
2. 2.16.840.1.113883.6.238 is the proper code system per regulation. Will confirm why the V3 set is used in FHIR and report back.

**Comment by Healthedata1** [comment]
Discussed today regardingi issue 1. (cardinality) and will add guidance for the Argonaut IG that states the [us-core-race extension ](http://hl7-fhir.github.io/extension-us-core-race.html)is in error and that the race/ethnicity may repeat.

e.g.

```
"extension" : [
  {
    "url" : "http://hl7.org/fhir/StructureDefinition/us-core-race",
   "valueCodeableConcept" : {
      "coding" : [
        {
          "system" : "http://hl7.org/fhir/v3/Race",
          "code" : "2106-3",
          "display" : "White"
        },
   {
    "url" : "http://hl7.org/fhir/StructureDefinition/us-core-race",
   "valueCodeableConcept" : {
      "coding" : [
        {
          "system" : "http://hl7.org/fhir/v3/Race",
          "code" : "2028-9",
          "display" : "Asian"
        },
        ....
```

**Comment by Healthedata1** [comment]
Drew,  Maybe I misunderstand your concern about the value sets, but I don't understand how a single value set can be used for both the race and ethnicity data-elements.  They have been defined as separate concepts by OMB.

From the  [2015 Edition Certification Companion Guide](https://www.healthit.gov/sites/default/files/2015Ed_CCG_CCDS.pdf):

> The CDC Race and Ethnicity Code Set Version 1.0 includes over 900 concepts for
> representing race and ethnicity, in which **921 reference race** and **43 reference ethnicity**.
> [see also 80 FR 16816] 

Defining a single value set for both is bad terminology practice because we will wind up with the race data elements containing ethnicity concepts and vice versa. Best to define them as two separate value sets.

**Comment by torresdrew** [comment]
I probably confused the issue by using the value set rather than the system. The code systems being used are the v3 race and v3 ethnicity, which doesn't seem to match with what is required by the 2015 edition. 

There should be 2 value sets, but the values inside of the value sets should be coming from the code system required.

**Comment by Healthedata1** [comment]
in FHIR we eschew OIDs in favor of urls.  they are equivalent as discussed in the[ introductory text for the V3 code system](http://hl7.org/fhir/terminologies-v3.html) in the FHIR specification.

**Comment by Healthedata1** [comment]
I will close this issue unless you want to discuss OIDs vs URLs further.

**Comment by brettmarquard** [comment]
My attempt to untangle is in ticket [#10237](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=10237).

Steps:
1. Add CDC Race and Ethnicity code system to the FHIR build (2.16.840.1.113883.6.238)
2. Create new VS http://hl7-fhir.github.io/Race/vs.html to include descendants of Race from the newly created code system
3. Create new VS http://hl7-fhir.github.io/Ethnicity/vs.html to include descendants of Ethnicity from the newly created code system
4. Remove http://hl7-fhir.github.io/v3/Race/cs.html
5. Remove http://hl7-fhir.github.io/v3/Race/vs.html
6. Remove http://hl7-fhir.github.io/v3/Ethnicity/cs.html
7. Remove http://hl7-fhir.github.io/v3/Ethnicity/vs.html

**Comment by torresdrew** [comment]
Thanks Brett! this add clarity around the situation.

**Comment by Healthedata1** [comment]
""

**Comment by brettmarquard** [comment]
Let's discuss within HL7.

**Comment by Healthedata1** [comment]
Dealt with within US Realm Task force and HL7 -  will update IGs to reflect.
