### ISSUE TITLE
What value set should be bound to CarePlan.participant.role

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#44]
What value set should be bound to [CarePlan.participant.role](http://hl7.org/fhir/careplan.html)

Requirements:
- Desire to harmonize with CCDA and Provider Directory
- non clinical and organization roles
- Binding strength = extensible

Choices:
1. [SNOMED-CT based](http://hl7.org/fhir/valueset-participant-role.html) ( Same as example binding in base )
2.  [NUCC](http://www.nucc.org/l)  +  SNOMED-CT Hybrid
   1.  NUCC for providers
   2.  SNOMED-CT for - non clinical and organization roles

**Comment by michelle-m-miller** [comment]
Can we add a requirement around licensing considerations?  

Is NUCC restricted to United States [1]? 

SNOMED is getting friendlier and easier to work with and receptive to new codes.  With SNOMED being more internationally popular, it feels like some mapping efforts can be reduced/reused for our clients in the global space (who might also leverage our FHIR services).  

[1] http://nucc.org/index.php?option=com_content&view=article&id=111&Itemid=110

**Comment by Healthedata1** [comment]
Well argonaut is US Realm and I think the Provider Directory group has
tackled the licensing issue.... Brett?

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by michelle-m-miller** [comment]
I understand Argonaut is US-realm, but I still support the goal of having as much alignment with international coding systems as possible to leverage/reuse terminology mappings, so I would still advocate that an international coding system is preferable to a US-only coding system when we have the option of using either one.

**Comment by brettmarquard** [comment]
The AMA license allows for incorporation and distribution in US. 

NUCC is required in both C-CDA, QRDA, and by many health plans for claims processing. The Argonaut PD members agreed to use NUCC for Practitioner.practitionerRole.role and Practitioner.practitionerRole.speciality.

Do we want to align with other US Requirements? Include both?

**Comment by Healthedata1** [comment]
I think including both would be:

  a) decreased interoperability in the  US  - if a choice of either

 b) too burdensome to be implemented  - if we went with an option to add a
translation  ( BUt I'll post to the Patient Admin list to see if maybe a
mapping between them exists?)

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by Healthedata1** [comment]
I created a[ value set definition](http://argonautwiki.hl7.org/index.php?title=CareTeam_Provider_Role_Value_Set)  for a hybrid NUCC + SNOMED  provider roles.   This is what I think it should be.

I asked on the list whether mappings exist and to date there is none that anybody is aware of.

**Comment by michelle-m-miller** [comment]
@Healthedata1 -- I thought we did get some initial mappings from John Davis (VA) between NUCC and SNOMED CT via the listserv?

**Comment by Healthedata1** [comment]
I have provided the [NUCC to SCT ConceptMap](http://argonautwiki.hl7.org/index.php?title=NUCC_to_SCT_Provider_Role_Mappings) for those who are interested.  Thanks to the folks at the VA.  We will publish the hybrid NUCC + SNOMED  value set in the IG with a link to the concept map
