### ISSUE TITLE
Whether the search for Patient Document's should be limited to current (active) documents?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#45]
The scope of the Document access is not defined regarding status of document which is a required element on the[ resource](http://hl7.org/fhir/documentreference.html).  For the minimal criteria do we want to require that the search return only  'current'  (=active) documents?

**Comment by jmandel** [comment]
By default (when `status` is omitted) the search should return all available documents (of any status). Now, a given EHR may choose not to make certain documents "available" in the first place, in which case they wouldn't appear no matter what search you wrote. But assuming an implicit status on these queries would be an error; said another way, a document should never appear in response to `GET /DocumentReference?patient=123&status=obsolete` if it doesn't appear in response to `GET /DocumentReference?patient=123`.

**Comment by torresdrew** [comment]
I do not think any such requirement should be in the IG. +1 to Josh's comments.

**Comment by Healthedata1** [comment]
I just want to clarify... if no status is provided then obsolete and
in-error documents may be returned.  But I'm hearing that is outside the
scope for the current IG.

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by Interopguy** [comment]
I would believe exception handling or out-of-bounds conditions should be in scope "for the client to address" if the server sends errant (non-conformant) results.  Albeit, these are considered edge cases, but if I were to build a client - I would want to know what I should do when error-conditions are encountered.  Is this what we are talking about?

**Comment by Healthedata1** [comment]
Nope.  we are discussing resource statuses.  Most resources have an
"entered-in error" status and I am asking if, in the minimal requirements
we are defining in the IG, whether limit the search to exclude the
"entered-in-error" and 'obsolete' statuses. In general, I  have asked for
each data query element.

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com
