### ISSUE TITLE
Whether to exchange the UDI string ("udi carrier") or DI + PI

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#47]
(creating this issue to track discusion on the Data Query call)

UDI as well as the DI and PI and need to parse the UDI is referenced in the MU regulations.  

> ...a Health IT Module certified to our proposed criterion would have to be able to parse certain “data elements from a UDI” and make these accessible to a user. 80 FR 16825...

However what exactly is the CCDS that needs to be exchanged via an API was unclear.  In the Data query call to review the  UDI IG it was decided the UDI string formally called the "udicarrier" is all that is required and there is no specific requirement to parse it into the DI and PI for exchange.

From the [2015 Edition Certification Companion Guide](https://www.healthit.gov/sites/default/files/2015Ed_CCG_CCDS.pdf)

> Unique device identifier(s) for a patient’s implantable device(s). In accordance with the “Product Instance” in the “Procedure Activity Procedure
> Section” of the standard specified in § 170.205(a)(4) for certification to the 2015 Edition health IT certification criteria.

 here is and example of Product Instance from C-CDA R2 Release 2.1

```
<participantRole classCode="MANU">
  <templateId root="2.16.840.1.113883.10.20.22.4.37"/>
  <id root="2.16.840.1.113883.3.3719"   
      extension="(01)51022222233336(11)141231(17)150707(10)A213B1(21)1234" 
      assigningAuthorityName="FDA"/>  
  <playingDevice>
    <code code="90412006" codeSystem="2.16.840.1.113883.6.96"   
          displayName="Colonoscope"/>
  </playingDevice>
  <scopingEntity>
    <id root="2.16.840.1.113883.3.3719"/>
  </scopingEntity>
</participantRole>
```

[Definitions of UDI related Data-Elements:](https://www.federalregister.gov/select-citation/2015/10/16/21-CFR-801.3)

**Comment by torresdrew** [comment]
I thought we decided on the last call to just expose the the UDI string. You can put examples of how to represent the parsed out pieces of the UDI, but the minimum requirement is to expose the UDI string.

**Comment by Healthedata1** [comment]
Hi Drew I'm going to document this and close it.  In case it comes up in the future
