### ISSUE TITLE
Whether the Immunization.status value-set should be constrained

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#49]
The DSTU Immuniization.status value set contains:

| Code | Display | Definition |
| --- | --- | --- |
| in-progress | In Progress | The administration has started but has not yet completed. |
| on-hold | On Hold | "Actions implied by the administration have been temporarily halted, but are expected to continue later. May also be called ""suspended""." |
| completed | Completed | All actions that are implied by the administration have occurred. |
| entered-in-error | Entered in Error | The administration was entered in error and therefore nullified. |
| stopped | Stopped | "Actions implied by the administration, have been permanently halted before all of them occurred." |

Since the many of these statuses are not valid for immunizations (the valueset was adopted from the MedicationAdministration resource), in STU3 the statuses will be limited to:

| Code | Display | Definition |
| --- | --- | --- |
| completed | Completed | All actions that are implied by the administration have occurred. |
| entered-in-error | Entered in Error | The administration was entered in error and therefore nullified. |

For the Argonaut IG we can constrain to these 2 status values.   The real question is whether implementers would erroneously use the other values in the DSTU2 version?

**Comment by jmandel** [comment]
It certainly seems to me like we should clarify in our implementation guide that only these two values are valid. That approach is consistent with DSTU2  as well as STU. Sounds like a win!

**Comment by daliboz** [comment]
After checking internally, found out we do return stopped and on hold from our server currently, but not for the reasons that were mentioned on the phone. For on hold, we have immunizations that are essentially only "temporary" not given, but will be given shortly (or the provider will ask the patient about giving the immunization in the future - ie, patient was sick and had to postpone). We return stopped for not given immunizations that will never be given (and the doctor will not ask the patient again)

**Comment by Healthedata1** [comment]
Jenni,

The PHER WG disposition on the GForge comment
http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=9070&start=0
clarifies how those case would be handled.

We will trim the allowed values to "completed" and "entered-in-error".  We

> will add clarification that the status refers to a specific vaccination
> event (including refusals).  The concepts of "refused" and "deferred" can
> be handled via reasonNotGiven

Eric
.

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by Healthedata1** [comment]
I have updated the IG to constrain the status to the two concepts listed above.  I have not closed this issue in order to give others a chance to chime in.

**Comment by Healthedata1** [comment]
Discussed on Data Query called no objections.
