### ISSUE TITLE
Whether to change effectiveDateTime/Period from a required to a must-support element?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#50]
The current MedicationStatement profile for Argonauts requires an effectiveDateTime/Period. However,  in a situation where Med Statements are patient-reported, very often an effectiveDateTime/Period is unknown or not documented (or we don’t have the confidence to document it in the system).
- Do other servers have this similar problem?
- Seeking feedback on the proposal to move effectiveDateTime/Period from a required to a must-support parameter?

**Comment by torresdrew** [comment]
I agree with the sentiment that this should change away from required. Dates for home meds are going to vary from system to system.

**Comment by Healthedata1** [comment]
Proposal to :
- add [dateAsserted](http://hl7.org/fhir/medicationstatement-definitions.html#MedicationStatement.dateAsserted)  as a mandatory element 
- change the [effective{x}](http://hl7.org/fhir/medicationstatement-definitions.html#MedicationStatement.effective_x_) to "[MUST SUPPORT](http://hl7.org/fhir/DSTU2/daf/daf.html#D.0.3.1%7C)" with a cardinality of 0..1

**Comment by brettmarquard** [comment]
[gForge #11983](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=11983&start=0)
