### ISSUE TITLE
Is DocumentReference the right resource for the Job?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#51]
Does DocumentReference  address the MU2015  [§ 170.315(g)(9) (Application Access—All Data Request)](https://www.healthit.gov/sites/default/files/170_315g9_application_access_all_data_request_v1_0_1.pdf) requirement?

A DocumentReference  based search would return a reference  or binary of a pre-existing indexed document.  On the 07/12 data query call, one interpretation of rule was that a custom query is required which would return  CCD document generated "on-demand".

**Comment by Healthedata1** [comment]
My interpretation is: 
-   § 170.315(g)(9) (I) (A) is like the  $everything operation but returns alls CCDS as a CCD either as a binary or a FHIR-CCD documents.  I agree it that is would be generated in response to the query. 
-  § 170.315(g)(9) (I) (B) is the DocumentReference part IF there are stored documents.  II am assuming part B) refers to the same data as in ( part A)

**Comment by torresdrew** [comment]
Cerner plans to implement the documentReference piece of this to allow a UI to display the existence of the CCD without generating the document each time. Binary with query parameters is how the consumer would actually retrieve the CCD.

**Comment by jmandel** [comment]
In the interest of keeping our surface area low, one approach would be just to have a `DocumentReference` to a "virtual" (not yet materialized anywhere) document. For example, it could have a title like "Current Clinical Summary (autogenerated)" or whatever, and it could point to its content via `content.attachment.url` (a given vendor might map this URL to, like "myserver/auto-generated.cgi?patien=123", or whatever); when the client fetches this URL, the data would be generated. We could even assign a specific category code to make this easier to search for the.

**Comment by daliboz** [comment]
@torresdrew @jmandel Technically, the consumer can query for the Doc Ref either via Binary or DocumentReference. However, from a "standard" way, I don't think that the Binary entry is really relevant here as long as the DocumentReference points somewhere.

@jmandel I think the outstanding question is _how does the consumer request the DocumentReference_ that is auto-generated. Your suggestion above doesn't define what the DocumentReference query looks like, rather just what it points to.

We've approached this (to differentiate between requesting a pre-generated CCD) with a custom query. EG: /DocumentReference?_query=auto-generate-ccd... Note: just an example query, I assume we would want to standardize on the query name. Parameters: patient id, loinc, optional date range.

Note: just saw your reference to a special category, but I think this feels better with a more explicit query definition rather than using a category that could collide later

**Comment by jmandel** [comment]
@daliboz can you clarify what you mean by colliding? If we define a proper category term, this should come with a system and code so that it would uniquely identify the meaning of this particular query. I'm not sure that adding a new operation accomplishes much in terms of functionality, given that we're effectively talking about getting a DocumentReference. But I'm happy to be convinced :-)

**Comment by Healthedata1** [comment]
Technically speaking what is being proposed sounds more like an operation since we asking a server to do something?

>  Operations are used (a) where the server needs to play an active role in formulating the content of the response, not merely return existing information

**Comment by jmandel** [comment]
I think technically speaking we could make either thing work! I'm not sure there's a very hard line and terms of capabilities here. Mostly I'm just wary of introducing new API syntax and infrastructure into the equation if it's  not buying us anything.

**Comment by Healthedata1** [comment]
So the proposal is something like

`/DocumentReference?patient= 123&class=autogen-ccd-if`

would return a reference to a patient's existing or virtual ccd?  

Which would be functionally the same as this operation;

`/DocumentReference$autogen-ccd-if?patient= 123`

**Comment by jmandel** [comment]
Yes, that's pretty much what we're talking about, @Healthedata1.

**Comment by Healthedata1** [comment]
So to clarify:  The DocumentReference would via an operation return metadata about a virtual document (like a ccd) and  would not result in the creation of a document instance.   In order to instantiate that document and retrieve it you would perform a second operation using the URL provided by the DocumentReference resource.    That URL would likely be Binary resource operation. 

So the proposal is something like:

`/DocumentReference$autogen-ccd-if?patient= 123`

From which you would get something like this URL which you could use to fetch the actual document...

`/Binary$autogen-ccd-if?patient= 123`

**Comment by daliboz** [comment]
@jmandel @Healthedata1 I assume we need some date range query params on there along with patient. And would these be required? Otherwise, what data does the service return?

**Comment by torresdrew** [comment]
Date range must be supported, but not required. The certification does test for date range functionality as part of the testing. Date ranges in the middle of an encounter is allowed include data that part of the encounter, and the technology is allowed to ignore the date parameter when it is in the patient's best interest. I.E. including all allergies irrelevant of date range. 

I would assume that a date range that isn't passed in results in a CCD that contains a CCD that is not bound to a date range.

**Comment by torresdrew** [comment]
Has the argonaut specifiers looked at defining some parameters for the OperationDefinition? 

Some fields that look that they should be defined by the IG for all implementers to implement:
URL: http://hl7.org/fhir/DSTU2/operationdefinition-definitions.html#OperationDefinition.url
Publisher: http://hl7.org/fhir/DSTU2/operationdefinition-definitions.html#OperationDefinition.publisher

**Comment by Healthedata1** [comment]
Thanks for feedback.   I was planning to be the upcoming HL7 meeting but I
crashed my bike and  will be at home recuperating and hope to have
something drafted soon.

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by dennispatterson** [comment]
@Healthedata1 I truly hope your recuperation has been progressing well!  I wanted to bump this thread for a moment and ask whether the autogen-ccd-if operation has been documented anywhere outside this issue?

**Comment by dennispatterson** [comment]
I spoke too soon!  It's in the [implementation guide](http://argonautwiki.hl7.org/index.php?title=Argonaut_Document_Access), just with some changes in syntax.

**Comment by jmandel** [comment]
http://argonautwiki.hl7.org/index.php?title=Argonaut_Document_Access points to a long list of document types, but I'm having trouble figuring out how to go from that to the most common requirement we'll have, which is a C-CDA Clinical Summary document. Can we explicitly list the code for a C-CDA Clinical Summary (and other doc types required by EHR certification) in our profile?

**Comment by jmandel** [comment]
Or if this isn't a question of `type` (e.g. maybe `format` is all that matters), spell out what the right query is. We don't seem to have a working example.

**Comment by Healthedata1** [comment]
I have been working on it here:
http://healthedatainc.com/go-ftp/Argo-DSTU2/structuredefinition-argo-documentreference.html

We are switching over to this site at the end of the year.  And I welcome
any feedback.  And I don't have any working examples of the operation.  I'm
not even sure if the GET example is valid anymore.  I will spell out the
CCD LOINC code 34133-9 in the text

Thanks,

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by Healthedata1** [comment]
I meant to switching over to a permanent fhir.org/guides  site.  This is
temporary (and switches my filenames to lowercase!!)

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by dennispatterson** [comment]
Operation name: The existing [argonaut wiki](http://argonautwiki.hl7.org/index.php?title=Argonaut_Document_Access) has the operation as $get-docref, while the [healthedatainc site](http://healthedatainc.com/go-ftp/Argo-DSTU2/structuredefinition-argo-documentreference.html) has $docref.  Can you confirm the latter is the intended operation?

LOINC:  Above you've mentioned 34133-9, but the [healthedatainc site](http://healthedatainc.com/go-ftp/Argo-DSTU2/operationdefinition-get-docref.html) mentions 48764-5.  81214-9 is another loinc we had identified as a possibility.

**Comment by Healthedata1** [comment]
The wiki site is for document reference is an earlier draft I'll updat it
to point the  Healthedata site since that is the latest. At this point I
can't keep them synced.   Re the LOINC in CCDA Release 2 R2.1 Vol2 p118
34133-9 is used.  I've CC'd Brett to confirm this.

Thanks,

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by torresdrew** [comment]
34133-9 makes sense for episodic level document, but this is a person level document and should be a more generic LOINC code. http://r.details.loinc.org/LOINC/81214-9.html?sections=Comprehensive makes a bit more sense.

**Comment by brettmarquard** [comment]
I am not familiar with 81214-9, it appears to be a 'panel' code for CCD R2.1 sections, not a document code. I believe 34133-9 is more appropriate.

**Comment by brettmarquard** [comment]
And, 48764-5 is an old 'Summary of Purpose' section code from the original CCD.

**Comment by Healthedata1** [comment]
updated IG and published
