### ISSUE TITLE
CarePlan date support

### ISSUE THREAD

**Issue by torresdrew** [argonautproject/implementation-program#52]
Do we really need to support date search? I recall concerns around longitudinal patient care plans. Is the intent for servers to support the query, but may choose to ignore the date portion of the query?

**Comment by Healthedata1** [comment]
Proposal to change the search by date requirement from mandatory to _SHOULD_ for both Server and Client or only  for Server to acccomodate  EHRs that only have longitudinal patient care plans?

**Comment by Healthedata1** [comment]
will remove the date based search criteria from the IGs
