### ISSUE TITLE
Procedure terminology and cardinality should be flexible. 

### ISSUE THREAD

**Issue by torresdrew** [argonautproject/implementation-program#54]
Looks like the way the profile is written today requires 1 coded value. We should allow for non coded responses to be returned. The code and coding element would not be populated for a free text procedure.

Cerner allows for 1 of 3 terminologies to be used when entering coded procedures(SNOMED, CPT, ICD-10). When 1 procedure code is selected there is no way to send translations to the other terminologies. This seems to be OK in the instance when SNOMED or CPT is selected, but when ICD-10 is selected, the IG implies that the ICD-10 code must accompany a SNOMED or CPT code which isn't a supported situation.

**Comment by jmandel** [comment]
DAF Procedure today uses a binding strength of "preferred", meaning that "Instances are encouraged to draw from the specified codes for interoperability purposes but are not required to do so to be considered conformant."

**Comment by michelle-m-miller** [comment]
Where do you see that Josh?

We were looking at http://hl7.org/fhir/us/daf/2016Sep/daf-core-procedure.html

"Based upon the 2015 Edition Certification Requirements, either SNOMED-CT or CPT-4/HCPC procedure codes are required and ICD-10-PCS codes MAY be supported as translations to them. If choosing to primarily to dental procedures, the Code on Dental Procedures and Nomenclature (CDT Code) may be used."

Also, in the Snapshot Table, one of the codings is 1..1 with a binding strength of required.

**Comment by brettmarquard** [comment]
Please submit a tracker for us to fix, agree with your excerpt from 2015 Rule.

Thanks

**Comment by michelle-m-miller** [comment]
http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=10766

**Comment by jmandel** [comment]
@michelle-m-miller I'm looking at http://hl7.org/fhir/daf/daf-procedure.html#tx:

![image](https://cloud.githubusercontent.com/assets/313089/18565387/94118384-7b5d-11e6-9258-396de87e5996.png)

**Comment by michelle-m-miller** [comment]
It changed in the Sept ballot version when slicing was introduced (minOccurs is now 1 and binding strength is required).  Per Brett's request, I logged the gForge (10766) to relax the binding strength and minOccurs.

**Comment by brettmarquard** [comment]
How do folks feel about making the binding extensible?

This would allow systems to send text when they don't have a code.

**Comment by torresdrew** [comment]
I don't have an objection to the proposal.

**Comment by Healthedata1** [comment]
#57 related to this
