### ISSUE TITLE
DocuementReference masterIdentifier required?

### ISSUE THREAD

**Issue by daliboz** [argonautproject/implementation-program#61]
It looks like we're requiring the _masterIdentifier_ for DocumentReference [1] though in previous conversation, we only had discussed the "typical" id field. Also, even the _id_ field must be generated for the documents that are generated on the fly (and not indexed/stored).

I'm wondering what the reasoning is behind the masterIdentifier requirement? Since even the _id_ in our server won't be able to be referenced again, this is likely not something we would be able to populate in any meaningful way.

**Comment by Healthedata1** [comment]
removed masterindentifier as a mandatory element made identifier a SHOULD if available.
