### ISSUE TITLE
Valueset for the formatcode being used is missing CCDA R2.1 value

### ISSUE THREAD

**Issue by torresdrew** [argonautproject/implementation-program#67]
http://hl7.org/fhir/DSTU2/valueset-formatcodes.html does not contain urn:hl7-org:sdwg:ccda-structuredBody:2.1

The IG http://www.fhir.org/guides/argonaut/r2/StructureDefinition-argo-documentreference.html is also still listing the wrong format code.

**Comment by brettmarquard** [comment]
This IG is fixed in the latest build: http://build.fhir.org/ig/Healthedata1/Argo-DSTU2/StructureDefinition-argo-documentreference.html

FHIR.org will be updated ‘soon’.

Value set in DSTU2 will remain.

STU3 also doesn’t include, I created tracker 12788 to add.

**Comment by torresdrew** [comment]
Thanks for the info I am pointing the team to use the correct IG: http://build.fhir.org/ig/Healthedata1/Argo-DSTU2/
