### ISSUE TITLE
Care team category cardinality should be less restrictive

### ISSUE THREAD

**Issue by torresdrew** [argonautproject/implementation-program#68]
http://build.fhir.org/ig/Healthedata1/Argo-DSTU2/StructureDefinition-argo-careteam.html

The IG shows a cardinality of 1..1. I thought we would allow for additional category types.

**Comment by michelle-m-miller** [comment]
Examples of "additional category types" may align with care team categories suggested in STU3's  http://build.fhir.org/valueset-care-team-category.html (i.e. encounter-specific, longitudinal-care coordination, etc.)

**Comment by Healthedata1** [comment]
OK will correct to 0..* with a required slice for careteam.

**Comment by Healthedata1** [comment]
committed update  using an invarient instead of slice

**Comment by Healthedata1** [comment]
for both careteam and careplan
